title = "Alex's Domain"
baseURL = "https://alexhova.github.io/"
languageCode = "en-us"
theme = "ananke"

[params]
  favicon = ""

  featured_image = "/images/toasters.png"
  background_color_class = "bg-black"
  github = "https://github.com/alexhova"
  linkedin = "https://www.linkedin.com/in/alex-hovancik/"
  recent_posts_number = 3